# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SportsBuff-Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SportsBuff-Demo
  pod 'Kingfisher', '~> 5.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'
  
  target 'SportsBuff-DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
